"""Manual config for one DistilBERT LoRA run.

Usually change `seed`, `run_name`, and `output_dir`. For HPO-style reruns, the
main knobs are `target_modules`, `lora_r`, `lora_alpha`, and `learning_rate`.
Keep `modules_to_save` covering the classifier head, or the saved adapter will
not contain the task head correctly.
"""

CONFIG = {
    "method": "lora",
    "run_name": "distilbert_lora_final_seed42",
    "model_name": "distilbert-base-uncased",
    "dataset_name": "Hate-speech-CNERG/hatexplain",
    "seed": 42,
    "data_fraction_seed": 42,
    "data_fraction": 1.0,
    "max_train_samples": None,
    "max_eval_samples": None,
    "max_test_samples": None,
    "output_dir": "outputs/distilbert_lora_final_seed42",
    "overwrite_output_dir": False,
    "run_test": True,
    "test_split_name": "test",
    "max_length": 128,
    "learning_rate": 0.0001,
    "num_train_epochs": 4.0,
    "per_device_train_batch_size": 16,
    "per_device_eval_batch_size": 32,
    "weight_decay": 0.01,
    "warmup_ratio": 0.06,
    "max_grad_norm": 1.0,
    "optim": "adamw_torch",
    "lr_scheduler_type": "linear",
    "eval_strategy": "epoch",
    "save_strategy": "epoch",
    "logging_strategy": "steps",
    "logging_steps": 20,
    "eval_steps": None,
    "save_steps": 500,
    "save_total_limit": 1,
    "load_best_model_at_end": True,
    "metric_for_best_model": "eval_f1_macro",
    "lower_is_better": False,
    "no_save_final_model": False,
    "mixed_precision": "none",
    "gradient_checkpointing": False,
    "class_weighting": "none",
    "early_stopping_patience": 2,
    "early_stopping_threshold": 0.001,
    "use_wandb": True,
    "wandb_project": "hate-speech-ft",
    "wandb_entity": "hoangbachbach05-the-australian-national-university",
    "wandb_mode": "online",
    "target_modules": ["q_lin", "k_lin", "v_lin", "out_lin"],
    "modules_to_save": ["pre_classifier", "classifier"],
    "lora_r": 16,
    "lora_alpha": 16,
    "lora_dropout": 0.0,
}
